/*
 * This file is generated by jOOQ.
*/
package com.bian.order.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Order implements Serializable {

    private static final long serialVersionUID = 1563714008;

    private ULong     id;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Timestamp deleteTime;
    private ULong     userId;
    private ULong     productId;
    private UInteger  price;
    private UByte     status;

    public Order() {}

    public Order(Order value) {
        this.id = value.id;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleteTime = value.deleteTime;
        this.userId = value.userId;
        this.productId = value.productId;
        this.price = value.price;
        this.status = value.status;
    }

    public Order(
        ULong     id,
        Timestamp createTime,
        Timestamp updateTime,
        Timestamp deleteTime,
        ULong     userId,
        ULong     productId,
        UInteger  price,
        UByte     status
    ) {
        this.id = id;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleteTime = deleteTime;
        this.userId = userId;
        this.productId = productId;
        this.price = price;
        this.status = status;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Timestamp getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(Timestamp deleteTime) {
        this.deleteTime = deleteTime;
    }

    public ULong getUserId() {
        return this.userId;
    }

    public void setUserId(ULong userId) {
        this.userId = userId;
    }

    public ULong getProductId() {
        return this.productId;
    }

    public void setProductId(ULong productId) {
        this.productId = productId;
    }

    public UInteger getPrice() {
        return this.price;
    }

    public void setPrice(UInteger price) {
        this.price = price;
    }

    public UByte getStatus() {
        return this.status;
    }

    public void setStatus(UByte status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Order (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleteTime);
        sb.append(", ").append(userId);
        sb.append(", ").append(productId);
        sb.append(", ").append(price);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
