/*
 * This file is generated by jOOQ.
 */
package com.bian.order.model.vo;


import lombok.Data;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;

import java.sql.Timestamp;
import java.time.LocalDateTime;

@Data
public class Product {

    private Long id;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private LocalDateTime deleteTime;
    private String name;
    private Integer stock;
    private Integer price;
}
