/*
 * This file is generated by jOOQ.
 */
package com.bian.order.model.vo;


import lombok.Data;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;
import java.time.LocalDateTime;


@Data
public class User {

    private Long id;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private LocalDateTime deleteTime;
    private String mobile;
    private String loginPwd;
    private String pwdSalt;
    private Long balance;

}
