server:
  port: 8881
spring:
  application:
    name: 'product'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.226.228:3306/product?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, mappings
