server:
  port: 8080
spring:
  application:
    name: 'order'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.226.228:3306/tcc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    prefer-ip-address: false

