/*
 * This file is generated by jOOQ.
*/
package com.bian.product.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Productstocktcc implements Serializable {

    private static final long serialVersionUID = 1770678337;

    private ULong     id;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Timestamp deleteTime;
    private Timestamp expireTime;
    private UInteger  stock;
    private Boolean   status;
    private ULong     tProductId;

    public Productstocktcc() {}

    public Productstocktcc(Productstocktcc value) {
        this.id = value.id;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleteTime = value.deleteTime;
        this.expireTime = value.expireTime;
        this.stock = value.stock;
        this.status = value.status;
        this.tProductId = value.tProductId;
    }

    public Productstocktcc(
        ULong     id,
        Timestamp createTime,
        Timestamp updateTime,
        Timestamp deleteTime,
        Timestamp expireTime,
        UInteger  stock,
        Boolean   status,
        ULong     tProductId
    ) {
        this.id = id;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleteTime = deleteTime;
        this.expireTime = expireTime;
        this.stock = stock;
        this.status = status;
        this.tProductId = tProductId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Timestamp getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(Timestamp deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Timestamp getExpireTime() {
        return this.expireTime;
    }

    public void setExpireTime(Timestamp expireTime) {
        this.expireTime = expireTime;
    }

    public UInteger getStock() {
        return this.stock;
    }

    public void setStock(UInteger stock) {
        this.stock = stock;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public ULong getTProductId() {
        return this.tProductId;
    }

    public void setTProductId(ULong tProductId) {
        this.tProductId = tProductId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Productstocktcc (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleteTime);
        sb.append(", ").append(expireTime);
        sb.append(", ").append(stock);
        sb.append(", ").append(status);
        sb.append(", ").append(tProductId);

        sb.append(")");
        return sb.toString();
    }
}
