/*
 * This file is generated by jOOQ.
*/
package com.bian.user.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userbalancetcc implements Serializable {

    private static final long serialVersionUID = 22597800;

    private ULong     id;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Timestamp deleteTime;
    private Timestamp expireTime;
    private Long      amount;
    private Byte      status;
    private ULong     tUserId;

    public Userbalancetcc() {}

    public Userbalancetcc(Userbalancetcc value) {
        this.id = value.id;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleteTime = value.deleteTime;
        this.expireTime = value.expireTime;
        this.amount = value.amount;
        this.status = value.status;
        this.tUserId = value.tUserId;
    }

    public Userbalancetcc(
        ULong     id,
        Timestamp createTime,
        Timestamp updateTime,
        Timestamp deleteTime,
        Timestamp expireTime,
        Long      amount,
        Byte      status,
        ULong     tUserId
    ) {
        this.id = id;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleteTime = deleteTime;
        this.expireTime = expireTime;
        this.amount = amount;
        this.status = status;
        this.tUserId = tUserId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Timestamp getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(Timestamp deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Timestamp getExpireTime() {
        return this.expireTime;
    }

    public void setExpireTime(Timestamp expireTime) {
        this.expireTime = expireTime;
    }

    public Long getAmount() {
        return this.amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public ULong getTUserId() {
        return this.tUserId;
    }

    public void setTUserId(ULong tUserId) {
        this.tUserId = tUserId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Userbalancetcc (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleteTime);
        sb.append(", ").append(expireTime);
        sb.append(", ").append(amount);
        sb.append(", ").append(status);
        sb.append(", ").append(tUserId);

        sb.append(")");
        return sb.toString();
    }
}
