/*
 * This file is generated by jOOQ.
*/
package com.bian.product.jooq;


import com.bian.product.jooq.tables.Product;
import com.bian.product.jooq.tables.Productstocktcc;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>product</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRODUCT_PRIMARY = Indexes0.PRODUCT_PRIMARY;
    public static final Index PRODUCTSTOCKTCC_FK_T_PRODUCT_TCC_STATUS_EXPTIME = Indexes0.PRODUCTSTOCKTCC_FK_T_PRODUCT_TCC_STATUS_EXPTIME;
    public static final Index PRODUCTSTOCKTCC_PRIMARY = Indexes0.PRODUCTSTOCKTCC_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", Product.PRODUCT_, new OrderField[] { Product.PRODUCT_.ID }, true);
        public static Index PRODUCTSTOCKTCC_FK_T_PRODUCT_TCC_STATUS_EXPTIME = Internal.createIndex("fk_t_product_tcc_status_exptime", Productstocktcc.PRODUCTSTOCKTCC, new OrderField[] { Productstocktcc.PRODUCTSTOCKTCC.STATUS, Productstocktcc.PRODUCTSTOCKTCC.EXPIRE_TIME }, false);
        public static Index PRODUCTSTOCKTCC_PRIMARY = Internal.createIndex("PRIMARY", Productstocktcc.PRODUCTSTOCKTCC, new OrderField[] { Productstocktcc.PRODUCTSTOCKTCC.ID }, true);
    }
}
