/*
 * This file is generated by jOOQ.
*/
package com.bian.product.jooq;


import com.bian.product.jooq.tables.Product;
import com.bian.product.jooq.tables.Productstocktcc;
import com.bian.product.jooq.tables.records.ProductRecord;
import com.bian.product.jooq.tables.records.ProductstocktccRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.ULong;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>product</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ProductRecord, ULong> IDENTITY_PRODUCT_ = Identities0.IDENTITY_PRODUCT_;
    public static final Identity<ProductstocktccRecord, ULong> IDENTITY_PRODUCTSTOCKTCC = Identities0.IDENTITY_PRODUCTSTOCKTCC;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = UniqueKeys0.KEY_PRODUCT_PRIMARY;
    public static final UniqueKey<ProductstocktccRecord> KEY_PRODUCTSTOCKTCC_PRIMARY = UniqueKeys0.KEY_PRODUCTSTOCKTCC_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ProductRecord, ULong> IDENTITY_PRODUCT_ = Internal.createIdentity(Product.PRODUCT_, Product.PRODUCT_.ID);
        public static Identity<ProductstocktccRecord, ULong> IDENTITY_PRODUCTSTOCKTCC = Internal.createIdentity(Productstocktcc.PRODUCTSTOCKTCC, Productstocktcc.PRODUCTSTOCKTCC.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = Internal.createUniqueKey(Product.PRODUCT_, "KEY_product_PRIMARY", Product.PRODUCT_.ID);
        public static final UniqueKey<ProductstocktccRecord> KEY_PRODUCTSTOCKTCC_PRIMARY = Internal.createUniqueKey(Productstocktcc.PRODUCTSTOCKTCC, "KEY_productstocktcc_PRIMARY", Productstocktcc.PRODUCTSTOCKTCC.ID);
    }
}
