/*
 * This file is generated by jOOQ.
*/
package com.bian.product.jooq;


import com.bian.product.jooq.tables.Productstocktcc;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product extends SchemaImpl {

    private static final long serialVersionUID = -2107858028;

    /**
     * The reference instance of <code>product</code>
     */
    public static final Product PRODUCT = new Product();

    /**
     * The table <code>product.product</code>.
     */
    public final com.bian.product.jooq.tables.Product PRODUCT_ = com.bian.product.jooq.tables.Product.PRODUCT_;

    /**
     * The table <code>product.productstocktcc</code>.
     */
    public final Productstocktcc PRODUCTSTOCKTCC = com.bian.product.jooq.tables.Productstocktcc.PRODUCTSTOCKTCC;

    /**
     * No further instances allowed
     */
    private Product() {
        super("product", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            com.bian.product.jooq.tables.Product.PRODUCT_,
            Productstocktcc.PRODUCTSTOCKTCC);
    }
}
