/*
 * This file is generated by jOOQ.
*/
package com.bian.product.jooq;


import com.bian.product.jooq.tables.Product;
import com.bian.product.jooq.tables.Productstocktcc;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in product
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>product.product</code>.
     */
    public static final Product PRODUCT_ = com.bian.product.jooq.tables.Product.PRODUCT_;

    /**
     * The table <code>product.productstocktcc</code>.
     */
    public static final Productstocktcc PRODUCTSTOCKTCC = com.bian.product.jooq.tables.Productstocktcc.PRODUCTSTOCKTCC;
}
