/*
 * This file is generated by jOOQ.
*/
package com.bian.order.jooq;


import com.bian.order.jooq.tables.Conflict;
import com.bian.order.jooq.tables.Order;
import com.bian.order.jooq.tables.Participant;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>order</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONFLICT_PRIMARY = Indexes0.CONFLICT_PRIMARY;
    public static final Index ORDER_IDX_ORDER_USER_ID_CT = Indexes0.ORDER_IDX_ORDER_USER_ID_CT;
    public static final Index ORDER_PRIMARY = Indexes0.ORDER_PRIMARY;
    public static final Index PARTICIPANT_IDX_ORDER_PARTICIPANT_ID = Indexes0.PARTICIPANT_IDX_ORDER_PARTICIPANT_ID;
    public static final Index PARTICIPANT_PRIMARY = Indexes0.PARTICIPANT_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONFLICT_PRIMARY = Internal.createIndex("PRIMARY", Conflict.CONFLICT, new OrderField[] { Conflict.CONFLICT.ID }, true);
        public static Index ORDER_IDX_ORDER_USER_ID_CT = Internal.createIndex("idx_order_user_id_ct", Order.ORDER_, new OrderField[] { Order.ORDER_.USER_ID, Order.ORDER_.CREATE_TIME }, false);
        public static Index ORDER_PRIMARY = Internal.createIndex("PRIMARY", Order.ORDER_, new OrderField[] { Order.ORDER_.ID }, true);
        public static Index PARTICIPANT_IDX_ORDER_PARTICIPANT_ID = Internal.createIndex("idx_order_participant_id", Participant.PARTICIPANT, new OrderField[] { Participant.PARTICIPANT.T_ORDER_ID }, false);
        public static Index PARTICIPANT_PRIMARY = Internal.createIndex("PRIMARY", Participant.PARTICIPANT, new OrderField[] { Participant.PARTICIPANT.ID }, true);
    }
}
