/*
 * This file is generated by jOOQ.
*/
package com.bian.order.jooq.tables.records;


import com.bian.order.jooq.tables.Conflict;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConflictRecord extends UpdatableRecordImpl<ConflictRecord> implements Record6<ULong, Timestamp, Timestamp, Timestamp, String, ULong> {

    private static final long serialVersionUID = 573019730;

    /**
     * Setter for <code>order.conflict.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>order.conflict.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>order.conflict.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>order.conflict.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>order.conflict.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>order.conflict.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>order.conflict.delete_time</code>.
     */
    public void setDeleteTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>order.conflict.delete_time</code>.
     */
    public Timestamp getDeleteTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>order.conflict.error_detail</code>. 资源冲突时的详细记录, 留作人工处理
     */
    public void setErrorDetail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>order.conflict.error_detail</code>. 资源冲突时的详细记录, 留作人工处理
     */
    public String getErrorDetail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>order.conflict.t_order_id</code>. 订单ID
     */
    public void setTOrderId(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>order.conflict.t_order_id</code>. 订单ID
     */
    public ULong getTOrderId() {
        return (ULong) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<ULong, Timestamp, Timestamp, Timestamp, String, ULong> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<ULong, Timestamp, Timestamp, Timestamp, String, ULong> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return Conflict.CONFLICT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Conflict.CONFLICT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Conflict.CONFLICT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Conflict.CONFLICT.DELETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Conflict.CONFLICT.ERROR_DETAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field6() {
        return Conflict.CONFLICT.T_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getErrorDetail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component6() {
        return getTOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getErrorDetail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value6() {
        return getTOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConflictRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConflictRecord value2(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConflictRecord value3(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConflictRecord value4(Timestamp value) {
        setDeleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConflictRecord value5(String value) {
        setErrorDetail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConflictRecord value6(ULong value) {
        setTOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConflictRecord values(ULong value1, Timestamp value2, Timestamp value3, Timestamp value4, String value5, ULong value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConflictRecord
     */
    public ConflictRecord() {
        super(Conflict.CONFLICT);
    }

    /**
     * Create a detached, initialised ConflictRecord
     */
    public ConflictRecord(ULong id, Timestamp createTime, Timestamp updateTime, Timestamp deleteTime, String errorDetail, ULong tOrderId) {
        super(Conflict.CONFLICT);

        set(0, id);
        set(1, createTime);
        set(2, updateTime);
        set(3, deleteTime);
        set(4, errorDetail);
        set(5, tOrderId);
    }
}
