/*
 * This file is generated by jOOQ.
*/
package com.bian.order.jooq.tables.records;


import com.bian.order.jooq.tables.Order;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderRecord extends UpdatableRecordImpl<OrderRecord> implements Record8<ULong, Timestamp, Timestamp, Timestamp, ULong, ULong, UInteger, UByte> {

    private static final long serialVersionUID = 295900173;

    /**
     * Setter for <code>order.order.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>order.order.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>order.order.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>order.order.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>order.order.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>order.order.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>order.order.delete_time</code>.
     */
    public void setDeleteTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>order.order.delete_time</code>.
     */
    public Timestamp getDeleteTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>order.order.user_id</code>. 下单用户ID
     */
    public void setUserId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>order.order.user_id</code>. 下单用户ID
     */
    public ULong getUserId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>order.order.product_id</code>. 产品ID
     */
    public void setProductId(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>order.order.product_id</code>. 产品ID
     */
    public ULong getProductId() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>order.order.price</code>. 实际支付金额
     */
    public void setPrice(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>order.order.price</code>. 实际支付金额
     */
    public UInteger getPrice() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>order.order.status</code>. 订单状态, 0为支付中, 1为交易完成, 2为全部资源已被撤销, 3为资源确认冲突
     */
    public void setStatus(UByte value) {
        set(7, value);
    }

    /**
     * Getter for <code>order.order.status</code>. 订单状态, 0为支付中, 1为交易完成, 2为全部资源已被撤销, 3为资源确认冲突
     */
    public UByte getStatus() {
        return (UByte) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<ULong, Timestamp, Timestamp, Timestamp, ULong, ULong, UInteger, UByte> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<ULong, Timestamp, Timestamp, Timestamp, ULong, ULong, UInteger, UByte> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return Order.ORDER_.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Order.ORDER_.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Order.ORDER_.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Order.ORDER_.DELETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field5() {
        return Order.ORDER_.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field6() {
        return Order.ORDER_.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return Order.ORDER_.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field8() {
        return Order.ORDER_.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component6() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component7() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value6() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value2(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value3(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value4(Timestamp value) {
        setDeleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value5(ULong value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value6(ULong value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value7(UInteger value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value8(UByte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord values(ULong value1, Timestamp value2, Timestamp value3, Timestamp value4, ULong value5, ULong value6, UInteger value7, UByte value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRecord
     */
    public OrderRecord() {
        super(Order.ORDER_);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(ULong id, Timestamp createTime, Timestamp updateTime, Timestamp deleteTime, ULong userId, ULong productId, UInteger price, UByte status) {
        super(Order.ORDER_);

        set(0, id);
        set(1, createTime);
        set(2, updateTime);
        set(3, deleteTime);
        set(4, userId);
        set(5, productId);
        set(6, price);
        set(7, status);
    }
}
