/*
 * This file is generated by jOOQ.
*/
package com.bian.order.jooq.tables.records;


import com.bian.order.jooq.tables.Participant;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParticipantRecord extends UpdatableRecordImpl<ParticipantRecord> implements Record7<ULong, Timestamp, Timestamp, Timestamp, Timestamp, String, ULong> {

    private static final long serialVersionUID = 588269724;

    /**
     * Setter for <code>order.participant.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>order.participant.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>order.participant.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>order.participant.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>order.participant.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>order.participant.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>order.participant.delete_time</code>.
     */
    public void setDeleteTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>order.participant.delete_time</code>.
     */
    public Timestamp getDeleteTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>order.participant.expire_time</code>. 预留资源过期时间
     */
    public void setExpireTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>order.participant.expire_time</code>. 预留资源过期时间
     */
    public Timestamp getExpireTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>order.participant.uri</code>. 预留资源确认URI
     */
    public void setUri(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>order.participant.uri</code>. 预留资源确认URI
     */
    public String getUri() {
        return (String) get(5);
    }

    /**
     * Setter for <code>order.participant.t_order_id</code>. 订单ID
     */
    public void setTOrderId(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>order.participant.t_order_id</code>. 订单ID
     */
    public ULong getTOrderId() {
        return (ULong) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<ULong, Timestamp, Timestamp, Timestamp, Timestamp, String, ULong> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<ULong, Timestamp, Timestamp, Timestamp, Timestamp, String, ULong> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return Participant.PARTICIPANT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Participant.PARTICIPANT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Participant.PARTICIPANT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Participant.PARTICIPANT.DELETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Participant.PARTICIPANT.EXPIRE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Participant.PARTICIPANT.URI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field7() {
        return Participant.PARTICIPANT.T_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getExpireTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component7() {
        return getTOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getExpireTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value7() {
        return getTOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value2(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value3(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value4(Timestamp value) {
        setDeleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value5(Timestamp value) {
        setExpireTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value6(String value) {
        setUri(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value7(ULong value) {
        setTOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord values(ULong value1, Timestamp value2, Timestamp value3, Timestamp value4, Timestamp value5, String value6, ULong value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParticipantRecord
     */
    public ParticipantRecord() {
        super(Participant.PARTICIPANT);
    }

    /**
     * Create a detached, initialised ParticipantRecord
     */
    public ParticipantRecord(ULong id, Timestamp createTime, Timestamp updateTime, Timestamp deleteTime, Timestamp expireTime, String uri, ULong tOrderId) {
        super(Participant.PARTICIPANT);

        set(0, id);
        set(1, createTime);
        set(2, updateTime);
        set(3, deleteTime);
        set(4, expireTime);
        set(5, uri);
        set(6, tOrderId);
    }
}
