/*
 * This file is generated by jOOQ.
*/
package com.bian.order.jooq.tables.records;


import com.bian.order.jooq.tables.Participant;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParticipantRecord extends UpdatableRecordImpl<ParticipantRecord> implements Record5<ULong, Timestamp, ULong, String, String> {

    private static final long serialVersionUID = -2066736839;

    /**
     * Setter for <code>order.participant.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>order.participant.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>order.participant.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>order.participant.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>order.participant.t_order_id</code>. 订单ID
     */
    public void setTOrderId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>order.participant.t_order_id</code>. 订单ID
     */
    public ULong getTOrderId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>order.participant.part_id</code>.
     */
    public void setPartId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>order.participant.part_id</code>.
     */
    public String getPartId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>order.participant.part_type</code>.
     */
    public void setPartType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>order.participant.part_type</code>.
     */
    public String getPartType() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, Timestamp, ULong, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, Timestamp, ULong, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return Participant.PARTICIPANT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Participant.PARTICIPANT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return Participant.PARTICIPANT.T_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Participant.PARTICIPANT.PART_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Participant.PARTICIPANT.PART_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component3() {
        return getTOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPartId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPartType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getTOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPartId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPartType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value2(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value3(ULong value) {
        setTOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value4(String value) {
        setPartId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value5(String value) {
        setPartType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord values(ULong value1, Timestamp value2, ULong value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParticipantRecord
     */
    public ParticipantRecord() {
        super(Participant.PARTICIPANT);
    }

    /**
     * Create a detached, initialised ParticipantRecord
     */
    public ParticipantRecord(ULong id, Timestamp createTime, ULong tOrderId, String partId, String partType) {
        super(Participant.PARTICIPANT);

        set(0, id);
        set(1, createTime);
        set(2, tOrderId);
        set(3, partId);
        set(4, partType);
    }
}
