/*
 * This file is generated by jOOQ.
*/
package com.bian.user.jooq;


import com.bian.user.jooq.tables.User;
import com.bian.user.jooq.tables.Userbalancetcc;
import com.bian.user.jooq.tables.records.UserRecord;
import com.bian.user.jooq.tables.records.UserbalancetccRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.ULong;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>user</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<UserRecord, ULong> IDENTITY_USER_ = Identities0.IDENTITY_USER_;
    public static final Identity<UserbalancetccRecord, ULong> IDENTITY_USERBALANCETCC = Identities0.IDENTITY_USERBALANCETCC;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_UNI_USER_MOBILE = UniqueKeys0.KEY_USER_UNI_USER_MOBILE;
    public static final UniqueKey<UserbalancetccRecord> KEY_USERBALANCETCC_PRIMARY = UniqueKeys0.KEY_USERBALANCETCC_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<UserRecord, ULong> IDENTITY_USER_ = Internal.createIdentity(User.USER_, User.USER_.ID);
        public static Identity<UserbalancetccRecord, ULong> IDENTITY_USERBALANCETCC = Internal.createIdentity(Userbalancetcc.USERBALANCETCC, Userbalancetcc.USERBALANCETCC.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER_, "KEY_user_PRIMARY", User.USER_.ID);
        public static final UniqueKey<UserRecord> KEY_USER_UNI_USER_MOBILE = Internal.createUniqueKey(User.USER_, "KEY_user_uni_user_mobile", User.USER_.MOBILE);
        public static final UniqueKey<UserbalancetccRecord> KEY_USERBALANCETCC_PRIMARY = Internal.createUniqueKey(Userbalancetcc.USERBALANCETCC, "KEY_userbalancetcc_PRIMARY", Userbalancetcc.USERBALANCETCC.ID);
    }
}
