/*
 * This file is generated by jOOQ.
*/
package com.bian.user.jooq;


import com.bian.user.jooq.tables.User;
import com.bian.user.jooq.tables.Userbalancetcc;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in user
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user.user</code>.
     */
    public static final User USER_ = com.bian.user.jooq.tables.User.USER_;

    /**
     * The table <code>user.userbalancetcc</code>.
     */
    public static final Userbalancetcc USERBALANCETCC = com.bian.user.jooq.tables.Userbalancetcc.USERBALANCETCC;
}
