/*
 * This file is generated by jOOQ.
 */
package com.bian.common.model.vo;


import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import lombok.Data;

import java.time.LocalDateTime;

@Data
public class VoProduct {

    private Long id;
    @JsonDeserialize(using = LocalDateTImeDeserializer.class)
    private LocalDateTime createTime;
    @JsonDeserialize(using = LocalDateTImeDeserializer.class)
    private LocalDateTime updateTime;
    @JsonDeserialize(using = LocalDateTImeDeserializer.class)
    private LocalDateTime deleteTime;
    private String name;
    private Integer stock;
    private Integer price;
}
