/*
 * This file is generated by jOOQ.
*/
package com.bian.product.order.jooq;


import com.bian.product.order.jooq.tables.Order;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in tcc
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tcc.order</code>.
     */
    public static final Order ORDER = com.bian.product.order.jooq.tables.Order.ORDER;
}
